# Generated by Django 4.1.4 on 2022-12-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
